# pre-commit run --all-files
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-added-large-files
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-json
        files: \.(json)$
    -   id: check-yaml
    -   id: mixed-line-ending
    -   id: end-of-file-fixer
        exclude: polyglot.py$
    -   id: trailing-whitespace
        exclude: polyglot.py$
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.10.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==19.10b0]
        args: [-t, py38]
-   repo: https://github.com/markdownlint/markdownlint
    rev: v0.11.0
    hooks:
    -   id: markdownlint
        args: [-s, .markdownlint.rb]
