name: Martin Thoma
markdown: rdiscount
pygments: true
paginate: 7
permalink: /:title
baseurl: "http://martinthoma.github.io/"
paginate_path: "page/:num"

# indextank settings
indextank_index: my_index
indextank_api_url: http://:myapikey@myapi.api.indextank.com

# these values are applied as regular expressions 
indextank_excludes: [index.html, 404.html, ^/secret/]

# RSS-generator
url: http://martin-thoma.com

category_dir: category
