name: Martin Thoma
markdown: rdiscount
pygments: true
paginate: 7
permalink: /:title
baseurl: "http://www.martin-thoma.de/blog"
paginate_path: "page/:num"

# these values are applied as regular expressions 
indextank_excludes: [index.html, 404.html, ^/secret/]

# RSS-generator
url: http://www.martin-thoma.de/blog

category_dir: category
