name: Martin Thoma
markdown: rdiscount
pygments: true
paginate: 7
permalink: /:title
baseurl: "http://martinthoma.github.io"
paginate_path: "page/:num"
rss_path: /feed
rss_name: index.html
category_dir: category
author_dir: author
