name: Martin Thoma
lsi: false
markdown: redcarpet
pygments: true
paginate: 7
permalink: /:title
baseurl: "http://www.martin-thoma.de/blog"
paginate_path: "page/:num"
rss_path: /feed
rss_name: index.html
category_dir: category
author_dir: author
