name: Martin Thoma
lsi: false
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "tables", "with_toc_data"]
highlighter: pygments
paginate: 7
permalink: /:title
baseurl: "//martin-thoma.com"
paginate_path: "page/:num"
rss_path: /feed
rss_name: index.html
category_dir: category
author_dir: author
description: A blog about Code, the Web and Cyberculture
encoding: utf-8